# configuration: common
spring:   
   mvc:
      throw-exception-if-no-handler-found: true
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 250MB
      
server:
   port: 0
   error:
      whitelabel:
         enabled: false
      path: /error   
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true