# configuration: default
spring:
   mvc:
      throw-exception-if-no-handler-found: true
      
mybatis:
   config-location: classpath:mybatis/configuration.xml

server:
   port: 0
   error:
      whitelabel:
         enabled: false
      path: /error
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true